apiVersion: v1
kind: Service
metadata:
  name: authservice
  namespace: {{ .Values.authservice.namespace }}
  
spec:
  type: ClusterIP
  ports:
  - name: http
    port: {{.Values.authservice.port.service}}
    targetPort: {{.Values.authservice.port.container}}  
    protocol: TCP
  selector:
    app: authservice
